.SUBCKT 6ka24 7 1
**************************************
*      Model Generated by MODPEX     *
*Copyright(c) Symmetry Design Systems*
*         All Rights Reserved        *
*    UNPUBLISHED LICENSED SOFTWARE   *
*   Contains Proprietary Information *
*      Which is The Property of      *
*     SYMMETRY OR ITS LICENSORS      *
*Commercial Use or Resale Restricted *
*   by Symmetry License Agreement    *
**************************************
* Model generated on Feb 21, 00
* MODEL FORMAT: PSPICE
*     anode cathode
*node: 7      1
*    Forward Section
D1 2 1 MDD1
.MODEL MDD1 D IS=7.37544e-14 N=1 XTI=1 RS=0.003 T_ABS=25
+ CJO=3e-10 TT=1e-08
*    Leakage Current
R 1 2 MDR 2.4e+08
.MODEL MDR RES (TC1=-0.005 TC2=0)
*    Breakdown
RZ 2 3 0.113468 
D3 4 3 MDD3
.MODEL MDD3 D T_ABS=25 IS=2.5e-15 N=0.5 
EV1 1 4 6 8 1
IBV 0 6 0.001
RBV 6 0 MDRBV 29700
.MODEL MDRBV RES (TC1=0.001)
D4 8 0 MDD3
L 7 2 1e-15
IT 0 8 0.1
.ENDS 6ka24
