.SUBCKT sm8a27 7 1
**************************************
*      Model Generated by MODPEX     *
*Copyright(c) Symmetry Design Systems*
*         All Rights Reserved        *
*    UNPUBLISHED LICENSED SOFTWARE   *
*   Contains Proprietary Information *
*      Which is The Property of      *
*     SYMMETRY OR ITS LICENSORS      *
*Commercial Use or Resale Restricted *
*   by Symmetry License Agreement    *
**************************************
* Model generated on Jul 21, 99
* MODEL FORMAT: PSPICE
*     anode cathode
*node: 7      1
*    Forward Section
D1 2 1 MDD1
.MODEL MDD1 D IS=2.13e-14 RS=8.9e-4 N=0.898
+EG=1 XTI=3 T_ABS=25 CJO=1e-11 TT=1e-08
*    Leakage Current
R 1 2 MDR 3.66667e+07
.MODEL MDR RES (TC1=-0.005 TC2=0)
*    Breakdown
RZ 2 3 0.13752 
D3 4 3 MDD3
.MODEL MDD3 D T_ABS=25 IS=2.5e-15 N=0.5 
EV1 1 4 6 8 1
IBV 0 6 0.001
RBV 6 0 MDRBV 27000
.MODEL MDRBV RES (TC1=0.00125)
D4 8 0 MDD3
L 7 2 1e-15
IT 0 8 0.01
.ENDS sm8a27
